import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className="bg-cyan-500">
					<p>AppName</p>
					<nav className="ml-3">
						<ul>
							<li>
								<a href="/">ホーム</a>
							</li>
							<li>
								<a href="/memos">ページ1</a>
							</li>
						</ul>
					</nav>
				</header>

				<main>{children}</main>

				<footer className="bg-cyan-500">
					<p>© 2025 My Memo App</p>
				</footer>
			</body>
		</html>
	);
}
